// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCerAmtB7e7uBi6hCOHQVO_QyBZ89Bc2LE',
    appId: '1:312902795955:web:2b0379f759cd960c65a6c6',
    messagingSenderId: '312902795955',
    projectId: 'hiyayakko-v2',
    authDomain: 'hiyayakko-v2.firebaseapp.com',
    storageBucket: 'hiyayakko-v2.appspot.com',
    measurementId: 'G-RLQC9QPMJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD255Wl1lDS0cjsXLTnHZsDzZ67-f8fPtU',
    appId: '1:312902795955:android:7af698d317acf4aa65a6c6',
    messagingSenderId: '312902795955',
    projectId: 'hiyayakko-v2',
    storageBucket: 'hiyayakko-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ECwJDV0jGwev3p3pAlW4EBPWs2GwazM',
    appId: '1:312902795955:ios:22f5b55de6853c7a65a6c6',
    messagingSenderId: '312902795955',
    projectId: 'hiyayakko-v2',
    storageBucket: 'hiyayakko-v2.appspot.com',
    iosClientId: '312902795955-daeeb23q4o6908upkd2l28784k7pt1ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiyayakko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ECwJDV0jGwev3p3pAlW4EBPWs2GwazM',
    appId: '1:312902795955:ios:6eb73eddc07e63c565a6c6',
    messagingSenderId: '312902795955',
    projectId: 'hiyayakko-v2',
    storageBucket: 'hiyayakko-v2.appspot.com',
    iosClientId: '312902795955-ue9764i5timc5p32dpth1v7i0lo65cgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiyayakko.RunnerTests',
  );
}
